version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb
      MYSQL_USER: shaziya
      MYSQL_PASSWORD: 1074
    ports:
      - "3307:3306"
    networks:
      - backend
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 30s
      retries: 3
      start_period: 30s

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
